<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Deterministic>true</Deterministic>
    <Version>0.1.0</Version>
    <InformationalVersion>0.1.0-alpha.1</InformationalVersion>
    <Authors>Faqra contributors</Authors>
    <Product>Faqra</Product>
    <Copyright>© 2026 Faqra contributors. Based on Vorssaint © 2026 Vorssaint, GPL-3.0-or-later.</Copyright>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>
</Project>
