// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Faqra contributors

namespace Faqra.Core.Localization;

public sealed partial class AgentsStrings
{
    public static AgentsStrings EnUS { get; } = new()
    {
        PageCaption = "Faqra watches your Claude Code sessions through hooks in Claude's settings. Nothing there changes until you review the exact edit and confirm it.",
        HooksSection = "Claude Code",
        HooksInstalled = "Hooks installed",
        HooksNotInstalled = "Hooks not installed",
        HooksOutdated = "Hooks need reinstalling",
        HooksCaptionFormat = "In {0}",
        CoucouLeftoversFormat = "Coucou's hooks still run on {0} of Claude Code's events. Installing can remove them.",
        ReviewInstall = "Review and install",
        ReviewRemove = "Remove hooks",
        RelayMissing = "Faqra's relay is missing from its folder, so the hooks can't be installed. Reinstall Faqra.",
        FileUnreadableFormat = "Faqra won't edit Claude's settings because they aren't plain JSON: {0}",
        Installed = "Hooks installed. New Claude Code sessions appear in the island.",
        Removed = "Hooks removed.",
        AlertsSection = "Alerts",
        NeedsYouSound = "Sound when an agent needs you",
        NeedsYouSoundCaption = "Plays the Windows notification sound when the island opens for an approval or a question.",
        AnsweredSound = "Sound when an agent answers",
        AnsweredSoundCaption = "Plays the Windows message sound when Claude finishes a turn.",
        OpenOnAnswer = "Open the island when an agent answers",
        OpenOnAnswerCaption = "Shows what Claude said without taking the keyboard from what you're doing.",
        ShortcutsToggle = "Keyboard shortcuts",
        ShortcutsCaption = "Open the waiting card, go to a session's window and switch sessions from anywhere. Change the keys on the Shortcuts page.",
        WatchOnly = "While Coucou's hooks are installed, Faqra only watches: approvals and questions stay in Claude Code.",
        ShortcutJump = "Open the waiting agent",
        ShortcutWindow = "Go to the agent's window",
        ShortcutNext = "Next agent session",
        ShortcutPrevious = "Previous agent session",
        ReviewTitle = "Review the change to Claude's settings",
        ReviewBackupFormat = "Faqra saves the current file as {0} before writing.",
        ReviewNewFile = "Claude's settings file doesn't exist yet, so Faqra creates it.",
        ReviewRemoveCoucou = "Also remove Coucou's hooks",
        ReviewConfirmInstall = "Install hooks",
        ReviewConfirmRemove = "Remove hooks",
        ReviewCancel = "Cancel",
        ReviewNoChange = "Nothing to change.",
        FileChanged = "Claude's settings changed since this preview. Here is the new version.",
        WriteFailedFormat = "Faqra couldn't write Claude's settings: {0}",
        EmptyTitle = "No agent sessions",
        EmptyHintNotInstalled = "Install the Claude Code hooks in Settings to see sessions here.",
        EmptyHintInstalled = "Start Claude Code and its sessions appear here.",
        OpenSettings = "Open settings",
        ActivityHeader = "Activity",
        LastMessageHeader = "Claude said",
        StateIdle = "Idle",
        StateThinking = "Thinking",
        StateWorking = "Working",
        StateSearching = "Searching",
        StateCompacting = "Compacting",
        StateBackgroundFormat = "Subagents running: {0}",
        StateApproval = "Needs your OK",
        StateQuestion = "Has a question",
        StateError = "Error",
        StateRateLimited = "Rate limited",
        StateFinished = "Done",
        ApprovalRun = "Wants to run a command",
        ApprovalEdit = "Wants to edit a file",
        ApprovalFetch = "Wants to open a web page",
        ApprovalToolFormat = "Wants to use {0}",
        StepPromptFormat = "Asked: {0}",
        StepReadFormat = "Reads {0}",
        StepEditFormat = "Edits {0}",
        StepRunFormat = "Runs {0}",
        StepSearchFormat = "Searches for {0}",
        StepWebSearchFormat = "Searches the web for {0}",
        StepWebFetchFormat = "Opens {0}",
        StepSubagentFormat = "Starts a subagent: {0}",
        StepSubagent = "Starts a subagent",
        StepSubagentDone = "A subagent finished",
        StepPlan = "Updates its plan",
        StepToolFormat = "Uses {0}",
        StepFailedFormat = "{0} failed",
        ElapsedNow = "now",
        ElapsedMinutesFormat = "{0} min",
        ElapsedHoursFormat = "{0} h",
    };
}
