// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Faqra contributors
// English values from Sources/Vorssaint/Core/FeatureHubStrings.swift, Core/Localization.swift and the
// per-feature *Strings.swift files. "Mac" wording is adapted to Windows where the feature is ported.

using Faqra.Core.Features;

namespace Faqra.Core.Localization;

public sealed partial class FeatureHubStrings
{
    public static FeatureHubStrings EnUS { get; } = new()
    {
        FeatureTitles = new Dictionary<AppFeature, string>
        {
            [AppFeature.Switcher] = "App switcher",
            [AppFeature.DockPreview] = "Dock Preview",
            [AppFeature.DockClick] = "Dock clicks",
            [AppFeature.WindowMaximizer] = "Maximize windows",
            [AppFeature.WindowLayout] = "Window layout",
            [AppFeature.AutoQuit] = "Quit on close",
            [AppFeature.ScrollInverter] = "Invert mouse scrolling",
            [AppFeature.FocusFollowsMouse] = "Focus follows mouse",
            [AppFeature.SmoothScroll] = "Smooth scrolling",
            [AppFeature.MouseAcceleration] = "Disable mouse acceleration",
            [AppFeature.MouseNavigation] = "Side buttons",
            [AppFeature.MouseButtonShortcuts] = "Mouse button shortcuts",
            [AppFeature.MiddleClick] = "Middle click",
            [AppFeature.MouseClickDebounce] = "Extra click filter",
            [AppFeature.KeyboardDebounce] = "Debounce",
            [AppFeature.TextSnippets] = "Text snippets",
            [AppFeature.SuperKey] = "Super key",
            [AppFeature.QuitWindowProtection] = "Quit & close protection",
            [AppFeature.ClipboardHistory] = "Clipboard",
            [AppFeature.PastePlain] = "Paste as plain text",
            [AppFeature.FinderCutPaste] = "Cut & paste",
            [AppFeature.FinderRename] = "Rename shortcut",
            [AppFeature.Shelf] = "Shelf",
            [AppFeature.UrlCleaner] = "Clean URL",
            [AppFeature.DiskImageInstaller] = "Disk image installer",
            [AppFeature.Mixer] = "Volume mixer",
            [AppFeature.SoundOutputSwitcher] = "Output switcher",
            [AppFeature.MicMute] = "Mute microphone",
            [AppFeature.MusicBlock] = "Music app blocker",
            [AppFeature.KeepAwake] = "Keep awake",
            [AppFeature.Brightness] = "Displays",
            [AppFeature.ExtraBrightness] = "Extra brightness",
            [AppFeature.BluetoothSleep] = "Bluetooth on sleep",
            [AppFeature.QuickLauncher] = "Quick panel",
            [AppFeature.QuickToggles] = "Quick toggles",
            [AppFeature.ColorPicker] = "Color picker",
            [AppFeature.ScreenOCR] = "Copy text from screen",
            [AppFeature.CleaningMode] = "Cleaning Mode",
            [AppFeature.MediaTools] = "Media",
            [AppFeature.Cleaner] = "Cleaner",
            [AppFeature.Uninstaller] = "Uninstaller",
            [AppFeature.Homebrew] = "Homebrew",
            [AppFeature.AppUpdates] = "App updates",
            [AppFeature.Screenshot] = "Screenshot",
            [AppFeature.CameraPreview] = "Camera preview",
            [AppFeature.RadialMenu] = "Radial menu",
            [AppFeature.Scratchpad] = "Scratchpad",
            [AppFeature.CommandBar] = "Command Bar",
            [AppFeature.ScreenRecorder] = "Screen recording",
            [AppFeature.KillProcess] = "Kill Process",
            [AppFeature.Notch] = "Dynamic Island",
            [AppFeature.NotchCalendar] = "Calendar",
            [AppFeature.NotchNotifications] = "Notifications",
            [AppFeature.NotchGestures] = "Dynamic Island Gestures",
            [AppFeature.NotchTimer] = "Timer",
            [AppFeature.NotchAccessories] = "Accessory alerts",
            [AppFeature.NotchLyrics] = "Lyrics",
            [AppFeature.NotchQueue] = "Up next",
            [AppFeature.NotchDownloads] = "Downloads",
            [AppFeature.MonitorCPU] = "CPU",
            [AppFeature.MonitorGPU] = "GPU",
            [AppFeature.MonitorMemory] = "Memory",
            [AppFeature.MonitorNetwork] = "Network",
            [AppFeature.MonitorDisk] = "Disks",
            [AppFeature.MonitorPower] = "Power",
            [AppFeature.FanControl] = "Fan Control",
        },
        FeatureDescriptions = new Dictionary<AppFeature, string>
        {
            [AppFeature.Switcher] = "Switch apps and windows with previews",
            [AppFeature.DockPreview] = "Window previews when hovering the Dock",
            [AppFeature.DockClick] = "Click a Dock icon to minimize or cycle windows",
            [AppFeature.WindowMaximizer] = "The green button maximizes instead of full screen",
            [AppFeature.WindowLayout] = "Arrange windows with shortcuts or edge snapping, then adjust them by dragging",
            [AppFeature.AutoQuit] = "Quit apps when their last window closes",
            [AppFeature.ScrollInverter] = "Invert the mouse wheel direction",
            [AppFeature.FocusFollowsMouse] = "Focuses and raises the window under the pointer after a short pause.",
            [AppFeature.SmoothScroll] = "Smooth, animated mouse scrolling",
            [AppFeature.MouseAcceleration] = $"Removes pointer acceleration for connected mice. Your previous setting returns when this is turned off or {AppInfo.Name} quits.",
            [AppFeature.MouseNavigation] = "Side mouse buttons go back and forward",
            [AppFeature.MouseButtonShortcuts] = "Extra buttons and side-wheel directions press a key combination you choose.",
            [AppFeature.MiddleClick] = "Three finger click acts as a middle click",
            [AppFeature.MouseClickDebounce] = "Ignores rapid extra clicks from worn mouse buttons without slowing normal clicks.",
            [AppFeature.KeyboardDebounce] = "Ignore accidental double key presses",
            [AppFeature.TextSnippets] = "Short triggers expand into full text",
            [AppFeature.SuperKey] = "Turns one key into the modifier combination you choose.",
            [AppFeature.QuitWindowProtection] = "Protects Alt+F4 and Ctrl+W from accidental presses",
            [AppFeature.ClipboardHistory] = "Keep a local history of what you copy",
            [AppFeature.PastePlain] = "Paste text without formatting",
            [AppFeature.FinderCutPaste] = "Cut and paste files in Finder",
            [AppFeature.FinderRename] = "Rename the selected file or folder with a shortcut you choose.",
            [AppFeature.Shelf] = "Drop files on the tray to hold them",
            [AppFeature.UrlCleaner] = "Copied links lose their tracking junk",
            [AppFeature.DiskImageInstaller] = "Install the single app inside a disk image and clean up the download",
            [AppFeature.Mixer] = "A volume slider for each app",
            [AppFeature.SoundOutputSwitcher] = "Cycle sound outputs with a shortcut",
            [AppFeature.MicMute] = "Mute the microphone from anywhere",
            [AppFeature.MusicBlock] = "Stop the Music app from launching itself",
            [AppFeature.KeepAwake] = "Keep the PC awake on demand",
            [AppFeature.Brightness] = "Brightness and power controls for every display",
            [AppFeature.ExtraBrightness] = "Extra brightness on HDR displays",
            [AppFeature.BluetoothSleep] = "Switches Bluetooth off while the PC sleeps, so headphones in a bag stop connecting to it.",
            [AppFeature.QuickLauncher] = "A floating panel with your favorite tools",
            [AppFeature.QuickToggles] = "One-click actions like dark mode and Recycle Bin",
            [AppFeature.ColorPicker] = "Pick any color on screen",
            [AppFeature.ScreenOCR] = "Copy text or QR codes from anything on screen",
            [AppFeature.CleaningMode] = "Lock keyboard and screen for cleaning",
            [AppFeature.MediaTools] = "Compress videos, images and GIFs",
            [AppFeature.Cleaner] = "Clear caches and junk files",
            [AppFeature.Uninstaller] = "Remove apps and their leftovers",
            [AppFeature.Homebrew] = "Keep Homebrew packages up to date",
            [AppFeature.AppUpdates] = "Find and install updates for the apps you have",
            [AppFeature.Screenshot] = "Captures an area, window or screen and annotates it",
            [AppFeature.CameraPreview] = "Opens a floating mirror with your camera",
            [AppFeature.RadialMenu] = "Opens a wheel of your favorite actions around the pointer",
            [AppFeature.Scratchpad] = "Floating pads for short-lived notes",
            [AppFeature.CommandBar] = "One field that finds and runs everything the app does",
            [AppFeature.ScreenRecorder] = "Records an area, window or screen and edits it afterwards",
            [AppFeature.KillProcess] = "Search running processes and force quit, restart, or kill process trees",
            [AppFeature.Notch] = "Your music, controls and everyday tools, together at the top of your screen. Optional. Turn it off to keep using the separate panels.",
            [AppFeature.NotchCalendar] = "Browse the month and your upcoming appointments in the Dynamic Island.",
            [AppFeature.NotchNotifications] = "New system notifications in the Dynamic Island.",
            [AppFeature.NotchGestures] = "Open and close the Dynamic Island with scrolling, and swipe to change tracks.",
            [AppFeature.NotchTimer] = "Timers and focused work sessions in the Dynamic Island.",
            [AppFeature.NotchAccessories] = "Show connected accessories and warn once when their battery falls to 20%.",
            [AppFeature.NotchLyrics] = "Follow the lyrics of the current song in the Dynamic Island.",
            [AppFeature.NotchQueue] = "See the actual upcoming songs shared by your player.",
            [AppFeature.NotchDownloads] = "See files arriving in a folder you choose, directly in the Dynamic Island.",
            [AppFeature.MonitorCPU] = "Processor usage and temperature",
            [AppFeature.MonitorGPU] = "Graphics usage and temperature",
            [AppFeature.MonitorMemory] = "Memory use and pressure",
            [AppFeature.MonitorNetwork] = "Network speed and usage",
            [AppFeature.MonitorDisk] = "Disk space and activity",
            [AppFeature.MonitorPower] = "Battery, power and charging",
            [AppFeature.FanControl] = "Control fans manually or with temperature curves while seeing live and target RPM",
        },
        GroupTitles = new Dictionary<FeatureGroup, string>
        {
            [FeatureGroup.WindowsDock] = "Windows and Dock",
            [FeatureGroup.MouseKeyboard] = "Mouse and keyboard",
            [FeatureGroup.ClipboardFiles] = "Clipboard and files",
            [FeatureGroup.Sound] = "Sound",
            [FeatureGroup.EnergyDisplay] = "Energy and display",
            [FeatureGroup.Tools] = "Tools",
            [FeatureGroup.Monitor] = "System monitor",
        },
        PresetNames = new Dictionary<FeaturePreset, string>
        {
            [FeaturePreset.Essential] = "Essentials",
            [FeaturePreset.Windows] = "Windows",
            [FeaturePreset.Battery] = "Battery and quiet",
        },
        PresetDescriptions = new Dictionary<FeaturePreset, string>
        {
            [FeaturePreset.Essential] = "Volume mixer, system monitor and keep awake.",
            [FeaturePreset.Windows] = "App switcher, window layout and the Dock features.",
            [FeaturePreset.Battery] = "A lean monitor with battery, memory and processor. Nothing listens to input.",
        },
        EnergyLabels = new Dictionary<FeatureEnergyProfile, string>
        {
            [FeatureEnergyProfile.Idle] = "Nothing at rest",
            [FeatureEnergyProfile.Mouse] = "Listens to the mouse",
            [FeatureEnergyProfile.Pointer] = "Listens to pointer input",
            [FeatureEnergyProfile.Keyboard] = "Listens to the keyboard",
            [FeatureEnergyProfile.Inputs] = "Listens to mouse and keyboard",
            [FeatureEnergyProfile.Periodic] = "Checks on an interval",
        },
        PermissionNames = new Dictionary<AppPermission, string>
        {
            [AppPermission.Accessibility] = "Accessibility",
            [AppPermission.ScreenRecording] = "Screen Recording",
            [AppPermission.FullDiskAccess] = "Full Disk Access",
            [AppPermission.FilesAndFolders] = "Files & Folders",
            [AppPermission.Notifications] = "Notifications",
            [AppPermission.AutomationFinder] = "Finder automation",
            [AppPermission.AutomationTerminal] = "Terminal automation",
            [AppPermission.AutomationPlayback] = "Playback automation",
            [AppPermission.AudioCapture] = "App audio",
            [AppPermission.Microphone] = "Microphone",
            [AppPermission.Camera] = "Camera",
            [AppPermission.AppManagement] = "App management",
            [AppPermission.Calendar] = "Calendar",
        },
        PermissionExplainers = new Dictionary<AppPermission, string>
        {
            [AppPermission.Accessibility] = "Lets features react to clicks and keys, and move windows.",
            [AppPermission.ScreenRecording] = "Lets features show window thumbnails and read text on screen.",
            [AppPermission.FullDiskAccess] = "Lets the cleaner and the uninstaller find leftover files everywhere.",
            [AppPermission.FilesAndFolders] = "Lets WhatsApp downloads cleanup and the experimental organizer inspect your Downloads folder.",
            [AppPermission.Notifications] = "Lets the app notify you about alerts you turned on.",
            [AppPermission.AutomationFinder] = "Lets the app ask Finder to move files for you.",
            [AppPermission.AutomationTerminal] = "Lets Homebrew commands open in Terminal.",
            [AppPermission.AutomationPlayback] = "Some music apps require permission for their playback controls.",
            [AppPermission.AudioCapture] = "Lets the mixer adjust each app's volume and screen recordings include the PC's sound.",
            [AppPermission.Microphone] = "Lets screen recordings include your voice when you turn it on.",
            [AppPermission.Camera] = "Shows your camera only in the preview window, so you can check how you look before a call. Nothing is recorded or leaves your PC.",
            [AppPermission.AppManagement] = "Lets updates replace or remove apps installed by the package manager.",
            [AppPermission.Calendar] = "Read your calendars to show upcoming appointments. Events stay on this PC.",
        },

        TabFeatures = "Features",
        TabPermissions = "Permissions",
        Intro = "Install only what you use. Whatever you uninstall disappears from the whole app and stops loading.",
        FooterNote = "Uninstalling deletes nothing: the feature just leaves the app and stops loading. "
            + "Install it again anytime and everything returns as it was.",
        MonitorAllOffNote = "With everything off, the Monitor leaves the panel and the tray.",
        InstalledCountFormat = "{0} of {1} features installed",
        InstallAll = "Install all",
        UninstallAll = "Uninstall all",
        Install = "Install",
        Uninstall = "Uninstall",
        BetaBadge = "Beta",
        EnergyHelp = "What the feature keeps alive while it is on. Uninstalled features load nothing at all.",

        RestartBannerText = "Uninstalled features stop working right away and leave memory on the next launch.",
        RestartBannerButton = "Restart now",

        PresetsTitle = "Start with a bundle",
        PresetsCaption = "One click sets the app up for how you use your PC. Everything else stays one click away.",
        PresetApplyButton = "Apply",
        PresetConfirmFormat = "Install the {0} bundle and uninstall the rest? Nothing is deleted, and everything comes back with one click.",
        PresetConfirmApply = "Apply bundle",
        PresetConfirmCancel = "Cancel",

        PermissionsIntro = "What each permission does and which features use it. Other access is requested only when you use it.",
        UsedByFormat = "Used by {0}",
        UsedByNone = "Nothing that is on uses this permission right now.",
        StatusGranted = "Granted",
        StatusMissing = "Not granted",
        StatusUnknown = "The app can't check this one",
        WindowsPermissionNote = "Windows does not gate these behind a consent prompt; this list shows what each feature touches.",
    };
}
