// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Faqra contributors
// Mirrors the English catalog in Sources/Vorssaint/Core/Localization.swift

namespace Faqra.Core.Localization;

public sealed partial class Strings
{
    public static Strings EnUS { get; } = new()
    {
        StatusIdleTooltip = $"{AppInfo.Name}: normal sleep",
        StatusActiveUntil = $"{AppInfo.Name}: awake until",
        StatusActiveIndefinite = $"{AppInfo.Name}: awake indefinitely",

        MenuEnableAwake = "Enable keep awake",
        MenuDisableAwake = "Disable keep awake",
        MenuActivateFor = "Activate for…",
        MenuSettings = "Settings…",
        MenuAbout = $"About {AppInfo.Name}",
        MenuQuit = $"Quit {AppInfo.Name}",
        MenuCheckUpdates = "Check for updates…",
        CleaningMenuItem = "Cleaning Mode",
        UninstallerMenuItem = "Uninstall an app…",
        ShelfMenuItem = "Open shelf",

        Minutes15 = "15 minutes",
        Minutes30 = "30 minutes",
        Hour1 = "1 hour",
        Hours2 = "2 hours",
        Hours4 = "4 hours",
        Hours8 = "8 hours",
        Indefinitely = "Indefinitely",
        KeepAwakeTitle = "Keep awake",

        FeatureNotAvailableOnWindows = "Not available on Windows",

        SettingsTitle = $"{AppInfo.Name} Settings",
        SettingsSearchPlaceholder = "Search settings",
        SettingsSectionTitles = new Dictionary<Settings.SettingsSection, string>
        {
            [Settings.SettingsSection.Essentials] = "Essentials",
            [Settings.SettingsSection.WindowControls] = "Window controls",
            [Settings.SettingsSection.Files] = "Files",
            [Settings.SettingsSection.AppManagement] = "App management",
            [Settings.SettingsSection.Utilities] = "Utilities",
            [Settings.SettingsSection.App] = "App",
        },
        SettingsPageTitles = new Dictionary<Settings.SettingsPage, string>
        {
            [Settings.SettingsPage.General] = "General",
            [Settings.SettingsPage.Features] = "Features",
            [Settings.SettingsPage.Energy] = "Energy",
            [Settings.SettingsPage.Monitor] = "Monitor",
            [Settings.SettingsPage.Mouse] = "Mouse & keyboard",
            [Settings.SettingsPage.Switcher] = "Switcher",
            [Settings.SettingsPage.KeyDebounce] = "Key debounce",
            [Settings.SettingsPage.SuperKey] = "Super key",
            [Settings.SettingsPage.CutPaste] = "Cut & paste",
            [Settings.SettingsPage.AutoQuit] = "Auto quit",
            [Settings.SettingsPage.QuitProtection] = "Quit protection",
            [Settings.SettingsPage.Cleaner] = "Cleaner",
            [Settings.SettingsPage.Uninstaller] = "Uninstaller",
            [Settings.SettingsPage.UrlCleaner] = "URL cleaner",
            [Settings.SettingsPage.Homebrew] = "Homebrew",
            [Settings.SettingsPage.AppUpdates] = "App updates",
            [Settings.SettingsPage.Media] = "Media",
            [Settings.SettingsPage.Clipboard] = "Clipboard",
            [Settings.SettingsPage.WindowLayout] = "Window layout",
            [Settings.SettingsPage.Shelf] = "Shelf",
            [Settings.SettingsPage.QuickTools] = "Quick panel",
            [Settings.SettingsPage.TextSnippets] = "Text snippets",
            [Settings.SettingsPage.Screenshot] = "Screen capture",
            [Settings.SettingsPage.RadialMenu] = "Radial menu",
            [Settings.SettingsPage.CommandBar] = "Command Bar",
            [Settings.SettingsPage.KillProcess] = "Kill process",
            [Settings.SettingsPage.Notch] = "Island",
            [Settings.SettingsPage.Agents] = "Agents",
            [Settings.SettingsPage.Shortcuts] = "Keyboard shortcuts",
            [Settings.SettingsPage.Advanced] = "Advanced",
            [Settings.SettingsPage.About] = "About",
        },

        LaunchAtLogin = "Launch at login",
        LaunchAtLoginNeedsApproval = "The startup entry exists but is switched off. Open Task Manager, go to Startup apps and enable "
            + AppInfo.Name + ".",
        LaunchAtLoginUnstableLocation = "The app is running from a place that cannot open at login. Move " + AppInfo.Name
            + " to a permanent folder, open it from there and turn this on again.",
        LanguageLabel = "Language",
        AppearanceLabel = "Appearance",
        AppearanceSystem = "System",
        AppearanceLight = "Light",
        AppearanceDark = "Dark",
        TraySection = "System tray",
        ShowTrayIcon = "Tray icon",
        ShowTrayIconHint = "Windows hides new tray icons in the overflow. Drag the icon onto the taskbar to keep it visible.",
        ShowTrayIconAction = "Show it again",

        IslandShow = "Show the island",
        IslandShowHint = "A small pill on the screen edge that opens when the pointer touches it.",
        IslandPosition = "Position",
        IslandPositionTop = "Top edge",
        IslandPositionLeft = "Left edge",
        IslandPositionRight = "Right edge",
        IslandDisplayLabel = "Display",
        IslandDisplayFollow = "Follow the pointer",
        IslandDisplayPrimary = "Primary display only",
        IslandOpenOnHover = "Open when the pointer touches it",
        IslandHoverExpands = "Hover opens it fully",
        IslandHoverExpandsHint = "Off means a hover shows a small preview, and a click opens the rest.",
        IslandSizeLabel = "Size",
        IslandSizeCompact = "Compact",
        IslandSizeSpacious = "Spacious",
        IslandIdleLabel = "When resting, show",
        IslandIdleMusic = "What is playing",
        IslandIdleBattery = "Battery",
        IslandIdleNone = "Nothing",

        BackupTitle = "Backup",
        BackupDescription = "Take your setup to another PC: export every preference to a file and import it there. "
            + "Your clipboard history and captured files never leave this PC.",
        BackupExportButton = "Export settings…",
        BackupImportButton = "Import settings…",
        BackupExported = "Backup saved",
        BackupInvalidFile = $"This file is not a valid {AppInfo.Name} backup.",
        BackupImportConfirmTitle = "Import these settings?",
        BackupImportConfirmBody = "Your current settings are replaced by the file's and the app restarts. Nothing else on this PC is touched.",
        BackupImportAction = "Import and restart",
        Cancel = "Cancel",

        OnboardingWelcomeTitle = $"Welcome to {AppInfo.Name}",
        OnboardingWelcomeBody = "A discreet tray utility that makes everyday Windows more practical.",
        OnboardingBullet1Title = "Energy under control",
        OnboardingBullet1Body = "Keep the PC awake for as long as you want, with or without the display.",
        OnboardingBullet2Title = "A clear view of the system",
        OnboardingBullet2Body = "Processor, graphics, memory, disk and network usage in real time.",
        OnboardingBullet3Title = "Sound, your way",
        OnboardingBullet3Body = "A volume slider for each app and one click to switch output device.",
        OnboardingPurposeTitle = "What brought you here?",
        OnboardingPurposeBody = "Choose a ready setup or select exactly what you want to use.",
        OnboardingPurposeSkip = "You can add or remove features later in Settings.",
        OnboardingDoneTitle = "All set!",
        OnboardingDoneBody = $"{AppInfo.Name} is already looking after your PC.",
        OnboardingDoneHint = "Look for the icon in the system tray, at the bottom right of the screen.",
        OnboardingBack = "Back",
        OnboardingContinue = "Continue",
        OnboardingStart = $"Open {AppInfo.Name}",

        AboutDescription = "A utility hub for your PC.\nEnergy, system monitor, mixer and a command bar, right in the system tray.",
        VersionPrefix = "Version",
        ViewOnGitHub = "View on GitHub",
        BetaBadgeLabel = "Beta",
        ReviewIntro = "Review introduction",
        ReviewHighlights = "Review highlights",
    };
}
