// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Faqra contributors
// Mirrors Sources/Vorssaint/Core/Defaults.swift (registeredDefaults, lines 916-1505) for the Stage 1 keys.

namespace Faqra.Core.Defaults;

public static partial class RegisteredDefaults
{
    /// <summary>Upstream's menu bar metric order; also the allow-list for MenuBarMetricOrder sanitizing.</summary>
    public static readonly IReadOnlyList<string> DefaultMenuBarMetricOrder =
    [
        "cpu", "cpuTemperature", "gpu", "gpuTemperature", "memory", "battery", "batteryTime", "batteryTemperature",
        "peripheralBattery", "network", "diskUsage", "diskActivity", "power", "fanSpeed",
    ];

    private static readonly IReadOnlyDictionary<string, object> Stage1Defaults = new Dictionary<string, object>(StringComparer.Ordinal)
    {
        // Appearance + startup
        [DefaultsKey.Appearance] = "system",
        [DefaultsKey.LiquidGlassEnabled] = false,
        [DefaultsKey.LaunchAtLoginWanted] = false,

        // Keep awake
        [DefaultsKey.DefaultDuration] = 0L,
        [DefaultsKey.BatteryLimit] = 10L,
        [DefaultsKey.KeepAwakeAutoStart] = false,
        [DefaultsKey.KeepAwakeRightClickToggle] = false,
        [DefaultsKey.KeepAwakeAllowDisplaySleep] = false,
        [DefaultsKey.KeepAwakeExternalDisplay] = false,
        [DefaultsKey.KeepAwakeConnectedToPower] = false,
        [DefaultsKey.KeepAwakeRunningApps] = false,
        [DefaultsKey.KeepAwakeRunningAppBundleIDs] = Array.Empty<string>(),
        [DefaultsKey.KeepAwakePauseWhenLocked] = false,
        [DefaultsKey.KeepAwakeMouseJiggleEnabled] = false,
        [DefaultsKey.KeepAwakeMouseJiggleInterval] = 5L,
        [DefaultsKey.HotkeyEnabled] = true,
        [DefaultsKey.KeepAwakeShortcut] = "control+option+command:75",   // Ctrl+Alt+Win+K (Windows VK)
        [DefaultsKey.KeepAwakeIconTint] = "orange",
        [DefaultsKey.KeepAwakeActiveIcon] = "vorssaint",
        [DefaultsKey.ShowCountdown] = false,
        [DefaultsKey.ClamshellPreferred] = false,

        // Updates
        [DefaultsKey.AutoCheckUpdates] = true,
        [DefaultsKey.IncludeBetaUpdates] = false,
        [DefaultsKey.ReleaseNotesOnUpdate] = true,
        [DefaultsKey.UpdateShowcaseIntroVersion] = "",
        [DefaultsKey.UpdateShowcaseMediaOverride] = "",

        // Mixer
        [DefaultsKey.MixerShowFinder] = true,
        [DefaultsKey.MixerHideInactiveApps] = false,
        [DefaultsKey.MixerLowerVolumeOnHeadphonesDisconnect] = false,
        [DefaultsKey.MixerHeadphonesDisconnectVolumePercent] = 25L,
        [DefaultsKey.PreciseVolumeRollerEnabled] = false,
        [DefaultsKey.SoundOutputSwitcherEnabled] = false,
        [DefaultsKey.SoundOutputSwitcherShortcut] = "control+option+command:83",  // Ctrl+Alt+Win+S (Windows VK)
        [DefaultsKey.MicMuteShortcutEnabled] = false,
        [DefaultsKey.MicMuteShortcut] = "control+option+command:77",  // Ctrl+Alt+Win+M (Windows VK)
        [DefaultsKey.MicMuteActive] = false,
        [DefaultsKey.MicMuteMenuBarIndicator] = true,
        [DefaultsKey.PanelToggleMicMute] = true,
        [DefaultsKey.MusicBlockEnabled] = false,
        [DefaultsKey.MusicBlockReplacementPath] = "",

        // Panel layout
        [DefaultsKey.PanelShowKeepAwake] = true,
        [DefaultsKey.PanelShowBrightness] = true,
        [DefaultsKey.PanelShowUtilities] = true,
        [DefaultsKey.PanelShowControls] = true,
        [DefaultsKey.PanelShowToggles] = true,
        [DefaultsKey.PanelShowFanControl] = true,
        [DefaultsKey.MonitorShowSystem] = true,
        [DefaultsKey.MonitorShowNetwork] = true,
        [DefaultsKey.MonitorShowDisk] = true,
        [DefaultsKey.MonitorShowPower] = true,
        [DefaultsKey.MonitorShowMixer] = true,
        [DefaultsKey.PanelNavigationEnabled] = true,
        [DefaultsKey.PanelControlNotch] = true,
        [DefaultsKey.PanelUtilityCommandBar] = true,

        // Menu bar metrics: off by default, the icon stays clean
        [DefaultsKey.MonitorInterval] = 2L,
        [DefaultsKey.TemperatureUnit] = "celsius",
        [DefaultsKey.MenuBarCPUTemperature] = false,
        [DefaultsKey.MenuBarGPUTemperature] = false,
        [DefaultsKey.MenuBarBatteryTemperature] = false,
        [DefaultsKey.MenuBarBatteryTime] = false,
        [DefaultsKey.MenuBarDiskUsage] = false,
        [DefaultsKey.MenuBarDiskActivity] = false,
        [DefaultsKey.MenuBarPeripheralBattery] = false,
        [DefaultsKey.MenuBarFanSpeed] = false,
        [DefaultsKey.MenuBarPreset] = "dense",
        [DefaultsKey.MenuBarMetricSpacing] = "compact",
        [DefaultsKey.MenuBarMetricAppearance] = "values",
        [DefaultsKey.MenuBarUsageBarNormalColor] = "#64D2FF",
        [DefaultsKey.MenuBarUsageBarElevatedColor] = "#FFD60A",
        [DefaultsKey.MenuBarUsageBarCriticalColor] = "#FF453A",
        [DefaultsKey.MenuBarUsageBarMediumThreshold] = 70L,
        [DefaultsKey.MenuBarUsageBarHighThreshold] = 90L,
        [DefaultsKey.MenuBarHideIconWithMetrics] = false,
        [DefaultsKey.MenuBarMetricOrder] = string.Join(",", DefaultMenuBarMetricOrder),
        [DefaultsKey.MenuBarCombineTemperatures] = true,
        [DefaultsKey.MenuBarSeparateMetrics] = false,
        [DefaultsKey.MenuBarNetworkUploadFirst] = false,
        [DefaultsKey.MenuBarLabelStyle] = "compact",
        [DefaultsKey.MenuBarMemoryStyle] = "percent",
        [DefaultsKey.MonitorMemoryMetric] = "used",

        // Monitor panel blocks
        [DefaultsKey.MonitorGraphCPU] = true,
        [DefaultsKey.MonitorGraphGPU] = true,
        [DefaultsKey.MonitorGraphMemory] = true,
        [DefaultsKey.MonitorGraphNetwork] = true,
        [DefaultsKey.MonitorGraphDisk] = true,
        [DefaultsKey.MonitorGraphPower] = true,
        [DefaultsKey.MonitorGraphBattery] = true,
        [DefaultsKey.MonitorSysTemps] = true,
        [DefaultsKey.MonitorSysCPU] = true,
        [DefaultsKey.MonitorSysGPU] = true,
        [DefaultsKey.MonitorSysBattery] = true,
        [DefaultsKey.MonitorSysMemory] = true,
        [DefaultsKey.MonitorSysAlerts] = true,
        [DefaultsKey.MonitorSysUptime] = true,
        [DefaultsKey.MonitorNetSpeed] = true,
        [DefaultsKey.MonitorNetApps] = true,
        [DefaultsKey.MonitorNetTotals] = true,
        [DefaultsKey.MonitorNetTest] = true,
        [DefaultsKey.MonitorDiskUsage] = true,
        [DefaultsKey.MonitorDiskActivity] = true,
        [DefaultsKey.MonitorDiskSMART] = true,
        [DefaultsKey.MonitorDiskProtection] = true,
        [DefaultsKey.MonitorDiskTools] = true,
        [DefaultsKey.MonitorPwrTemperature] = true,
        [DefaultsKey.MonitorPwrSystem] = true,
        [DefaultsKey.MonitorPwrAdapter] = true,
        [DefaultsKey.MonitorPwrBattery] = true,
        [DefaultsKey.MonitorPwrTimeRemaining] = true,
        [DefaultsKey.MonitorPwrHealth] = true,
        [DefaultsKey.MonitorAlertCPU] = false,
        [DefaultsKey.MonitorAlertCPUTemperature] = false,
        [DefaultsKey.MonitorAlertBatteryTemperature] = false,
        [DefaultsKey.MonitorAlertMemory] = false,
        [DefaultsKey.MonitorAlertDisk] = false,
        [DefaultsKey.MonitorAlertBattery] = false,
        [DefaultsKey.MonitorAlertCPUThreshold] = 90L,
        [DefaultsKey.MonitorAlertCPUTemperatureThreshold] = 90L,
        [DefaultsKey.MonitorAlertBatteryTemperatureThreshold] = 40L,
        [DefaultsKey.MonitorAlertDiskFreePercent] = 10L,
        [DefaultsKey.MonitorAlertBatteryPercent] = 15L,
        [DefaultsKey.MonitorAlertCooldownMinutes] = 15L,

        // Notch (island). NotchEnabled lives in CoreDefaults (deliberate deviation: on).
        [DefaultsKey.NotchDisplay] = "automatic",
        [DefaultsKey.IslandEdge] = "top",
        [DefaultsKey.NotchSize] = "spacious",
        [DefaultsKey.NotchCustomWidth] = 440L,
        [DefaultsKey.NotchCustomHeight] = 480L,
        [DefaultsKey.NotchShowPlayingMusic] = true,
        [DefaultsKey.NotchIdleContent] = "music",
        [DefaultsKey.NotchHiddenControls] = "",
        [DefaultsKey.NotchControlOrder] = "",
        [DefaultsKey.NotchHapticFeedback] = true,
        [DefaultsKey.NotchShelf] = true,
        [DefaultsKey.NotchDragReveal] = true,
        [DefaultsKey.NotchCaptureControls] = true,
        [DefaultsKey.NotchQuickPanel] = true,
        [DefaultsKey.NotchAppPanel] = true,
        [DefaultsKey.NotchHoverExpands] = true,
        [DefaultsKey.NotchOpenOnHover] = true,
        [DefaultsKey.NotchGesturesEnabled] = true,
        [DefaultsKey.NotchKeyboardLight] = false,
        [DefaultsKey.NotchNotificationsEnabled] = false,
        [DefaultsKey.NotchDismissNativeNotifications] = false,
        [DefaultsKey.NotchTimerEnabled] = true,
        [DefaultsKey.NotchTimerMode] = "timer",
        [DefaultsKey.NotchTimerSoundEnabled] = true,
        [DefaultsKey.NotchPomodoroFocusMinutes] = 25L,
        [DefaultsKey.NotchPomodoroShortBreakMinutes] = 5L,
        [DefaultsKey.NotchPomodoroLongBreakMinutes] = 15L,
        [DefaultsKey.NotchPomodoroLongBreakInterval] = 4L,
        [DefaultsKey.NotchPomodoroTotalSessions] = 4L,
        [DefaultsKey.NotchCameraEnabled] = false,
        [DefaultsKey.NotchAccessoriesEnabled] = false,
        [DefaultsKey.NotchCalendarEnabled] = true,
        [DefaultsKey.NotchLyricsEnabled] = false,
        [DefaultsKey.NotchLyricsOnline] = false,
        [DefaultsKey.NotchQueueEnabled] = false,
        [DefaultsKey.NotchDownloadsEnabled] = false,
        [DefaultsKey.NotchHiddenModules] = "",
        [DefaultsKey.NotchModuleOrder] = "",
        [DefaultsKey.NotchQuickAccessLayout] = Array.Empty<byte>(),
        [DefaultsKey.NotchVolume] = true,
        [DefaultsKey.NotchBrightness] = true,
        [DefaultsKey.NotchBattery] = true,
        [DefaultsKey.NotchClipboard] = false,
        [DefaultsKey.NotchClipboardWindow] = true,
        [DefaultsKey.NotchCapture] = false,
        [DefaultsKey.NotchMusicActivity] = false,
        [DefaultsKey.NotchShowInCaptures] = true,
        [DefaultsKey.NotchHideInCaptures] = false,

        // Command bar
        [DefaultsKey.CommandBarShortcutEnabled] = false,
        [DefaultsKey.CommandBarShortcut] = "option:32",  // Alt+Space (Windows VK)
        [DefaultsKey.CommandBarCompactMode] = false,
        [DefaultsKey.CommandBarDisabledSources] = "",
        [DefaultsKey.CommandBarAliases] = "",
        [DefaultsKey.CommandBarPins] = "",
        [DefaultsKey.CommandBarHidden] = "",
        [DefaultsKey.CommandBarPositionOffset] = "",
        [DefaultsKey.CommandBarFileScopes] = "",
        [DefaultsKey.CommandBarFileIgnores] = "",
        [DefaultsKey.KillProcessCommandBarEnabled] = true,

        // App updates utility
        [DefaultsKey.AppUpdatesCheckFrequency] = "off",
        [DefaultsKey.AppUpdatesNotify] = true,
    };
}
