<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RootNamespace>Faqra.Services</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Faqra.Core/Faqra.Core.csproj" />
    <ProjectReference Include="../Faqra.Win32/Faqra.Win32.csproj" />
  </ItemGroup>
</Project>
